### ISSUE TITLE
bug-report-desktop

### ISSUE THREAD

**Issue by Nevu** [suburb-kids/suburb-kids.github.io#1]
hey ho, ich weiß nicht ob ich guthub hier richtig raffe, oder wo die bugreportings hinkommen ... aber anbei mal ein image: muss das so sein? gruß o
![lineendings](https://cloud.githubusercontent.com/assets/2456068/8451399/58000b30-1fe3-11e5-9f3e-d0a15a0eae98.png)

**Comment by tonekk** [comment]
Heyho, wie kommst du auf dieses Repo?
Issues bitte hier hin posten: https://github.com/AgProp/biervisualisierung/issues

Desweiteren empfehle ich folgendes zu lesen: http://www.chiark.greenend.org.uk/~sgtatham/bugs-de.html

Der Screenshot ist schon super, aber 'bug-report-desktop' ist ein absolut sinnfreier Titel und ich bräuchte auch eine Beschreibung, was bisher passiert ist
